# Generated by Django 5.0.4 on 2024-04-27 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=20),
        ),
    ]
